version: 2

jobs:
  test-clj:
    docker:
      - image: circleci/clojure:lein-2.8.1

    # this is needed because inside the docker container $TERM
    # is not defined
    environment:
      - TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}

      - run: lein deps
      - run: lein eastwood
      - run: lein cljfmt check
      - run: lein test
      - save_cache:
          paths:
            - ~/.m2/repository
            - ~/.lein

          key: clj-deps-{{ checksum "project.clj" }}

  coverage:
    docker:
      - image: circleci/clojure:lein-2.8.1

    environment:
      - TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - clj-deps-{{ checksum "project.clj" }}
  
      - run: lein cloverage --codecov
      - store_test_results:
          path: target/test-results

      - store_artifacts:
          path: target/coverage

      - run: bash <(curl -s https://codecov.io/bash)

  test-cljs:
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - run: sudo npm install -g lumo-cljs
      - run: ./lumo-test
        
workflows:
  version: 2
  test:
    jobs:
      - test-clj
      - test-cljs
      - coverage
